"""registry and read models

Revision ID: 5d5bab6ded76
Revises: 
Create Date: 2026-09-29 17:54:16.561069
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5d5bab6ded76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('sport', sa.String(length=60), nullable=False),
    sa.Column('competition', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('live_binding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_event_start_utc'), 'event', ['start_utc'], unique=False)
    op.create_index(op.f('ix_event_status'), 'event', ['status'], unique=False)
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_hash')
    )
    op.create_index(op.f('ix_news_item_published'), 'news_item', ['published'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sport', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('teams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wikidata_qid', sa.String(length=20), nullable=True),
    sa.Column('disambiguation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sport', sa.String(length=60), nullable=False),
    sa.Column('competitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_player',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'player_id')
    )
    op.create_index(op.f('ix_event_player_player_id'), 'event_player', ['player_id'], unique=False)
    op.create_table('event_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_label', sa.String(length=200), nullable=True),
    sa.Column('clock_label', sa.String(length=100), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('snapshot_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_state_event_asof', 'event_state', ['event_id', 'as_of'], unique=False)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('alert_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fan_id', 'player_id')
    )
    op.create_index(op.f('ix_follow_fan_id'), 'follow', ['fan_id'], unique=False)
    op.create_index(op.f('ix_follow_player_id'), 'follow', ['player_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_player_id'), 'membership', ['player_id'], unique=False)
    op.create_index(op.f('ix_membership_team_id'), 'membership', ['team_id'], unique=False)
    op.create_table('news_player',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'player_id')
    )
    op.create_table('player_alias',
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_index(op.f('ix_player_alias_player_id'), 'player_alias', ['player_id'], unique=False)
    op.create_table('player_card',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('card', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('freshness', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_player_card_is_live'), 'player_card', ['is_live'], unique=False)
    op.create_table('player_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system', 'external_id')
    )
    op.create_index(op.f('ix_player_identity_player_id'), 'player_identity', ['player_id'], unique=False)
    op.create_table('player_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_line_player_event', 'player_line', ['player_id', 'event_id'], unique=False)
    op.create_table('source_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('adapter', sa.String(length=60), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('health', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_binding_player_id'), 'source_binding', ['player_id'], unique=False)
    op.create_index(op.f('ix_source_binding_team_id'), 'source_binding', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_binding_team_id'), table_name='source_binding')
    op.drop_index(op.f('ix_source_binding_player_id'), table_name='source_binding')
    op.drop_table('source_binding')
    op.drop_index('ix_player_line_player_event', table_name='player_line')
    op.drop_table('player_line')
    op.drop_index(op.f('ix_player_identity_player_id'), table_name='player_identity')
    op.drop_table('player_identity')
    op.drop_index(op.f('ix_player_card_is_live'), table_name='player_card')
    op.drop_table('player_card')
    op.drop_index(op.f('ix_player_alias_player_id'), table_name='player_alias')
    op.drop_table('player_alias')
    op.drop_table('news_player')
    op.drop_index(op.f('ix_membership_team_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_player_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_follow_player_id'), table_name='follow')
    op.drop_index(op.f('ix_follow_fan_id'), table_name='follow')
    op.drop_table('follow')
    op.drop_index('ix_event_state_event_asof', table_name='event_state')
    op.drop_table('event_state')
    op.drop_index(op.f('ix_event_player_player_id'), table_name='event_player')
    op.drop_table('event_player')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_index(op.f('ix_news_item_published'), table_name='news_item')
    op.drop_table('news_item')
    op.drop_index(op.f('ix_event_status'), table_name='event')
    op.drop_index(op.f('ix_event_start_utc'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
